@startuml

actor Controller

Controller -> moveCabinCommand: execute(HashMap<String, Object>)
activate moveCabinCommand
moveCabinCommand -> Engine: change engineState to GOING_DOWN
deactivate moveCabinCommand

@enduml
