@startuml

actor CloseDoorCommand

CloseDoorCommand -> Shaft: closeCabinDoor()
activate Shaft
Shaft -> Cabin: closeDoor()
Shaft -> Shaft: fireDoorState()
Shaft -> CabinService: handleDoorStateChanged(event)
CabinService -> ShaftRepository: updateDoorStateById(id, DoorState)
Shaft -> ElevatorDriver: handleDoorStateChanged(event)
deactivate Shaft

@enduml
